### ISSUE TITLE
Exec[chocolatey_autouninstaller_enable] always runs because unless command don't work

### ISSUE THREAD

**Issue by pesetskyps** [chocolatey/puppet-chocolatey#138] opened 2016-07-28 09:56 UTC
```
unless      => "cmd.exe /c ${_choco_exe_path} feature list -r | findstr /B /I /C:\"autoUninstaller - [${_enable_autouninstaller}d]\"",
```
The output of the command in version 0.9.10.3 ```choco feature list -r``` is like:
autoUninstaller|Enabled|Uninstall.
I think we should find ```autoUninstaller|${_enable_autouninstaller}d\"```

**Comment by ferventcoder** [comment] 2016-07-28 22:15
#134

**Comment by ferventcoder** [comment] 2016-07-28 22:16
You may want to upgrade to 1.2.6

**Comment by ferventcoder** [comment] 2016-07-28 22:16
This appears to be a duplicate of #134

**Comment by ferventcoder** [comment] 2016-07-28 22:17
Can you confirm this is the case so we can close this issue?

**Comment by ferventcoder** [comment] 2016-07-28 22:17
Thanks!

**Comment by ferventcoder** [comment] 2016-09-01 18:54
Closing due to inactivity. @pesetskyps if you determined this was not fixed by upgrading, please feel free to reopen and comment. Thanks!

**Closed by ferventcoder** 2016-09-01 18:54 UTC
Labels: Duplicate Issue
