### ISSUE TITLE
Way to manage chocolatey sources

### ISSUE THREAD

**Issue by mmarseglia** [chocolatey/puppet-chocolatey#126] opened 2016-06-06 20:38 UTC
I'd like a way to manage chocolatey sources and specifically disable the default source.

**Comment by ferventcoder** [comment] 2016-06-06 20:47
https://forge.puppet.com/puppetlabs/chocolatey#sources-configuration

**Comment by ferventcoder** [comment] 2016-06-06 20:53
Catch the head fake there - this is a Puppet, Inc. unsupported module release moving towards a supported module - https://github.com/puppetlabs/puppetlabs-chocolatey

**Comment by ferventcoder** [comment] 2016-06-06 20:54
https://tickets.puppetlabs.com/browse/MODULES-3037

And take a look at the Epic for Chocolatey - https://tickets.puppetlabs.com/browse/MODULES-3036

**Comment by ferventcoder** [comment] 2016-06-06 20:56
Note the very first example: 

~~~puppet
chocolateysource {'chocolatey':
  ensure => disabled,
}
~~~

**Comment by ferventcoder** [comment] 2016-06-06 20:58
Closing as a duplicate of PUP-3428 (which became MODULES-3037).

Also I had a PR on this before I decided we needed to go a different direction -  https://github.com/chocolatey/puppet-chocolatey/pull/79

**Closed by ferventcoder** 2016-06-06 20:58 UTC
Labels: Duplicate Issue
