### ISSUE TITLE
Interaction with user (MsgBox)

### ISSUE THREAD

**Issue by peterbeck** [chocolatey/puppet-chocolatey#127] opened 2016-06-06 22:46 UTC
Hi guys,

I have a package which should ensure the program in question is not running.
So I made a powershell script with some balloon-tips which is working fine - when using cinst.
But when the package is deployed with puppet, everything, including the balloon-tips are hidden.
The setup is completely silent - no user interaction needed. I just would like to tell them "hey, we are just installing package xy, do not start the application".... finally it (should) look like this;

![traymsg](https://cloud.githubusercontent.com/assets/561186/15840257/0903cec2-2c49-11e6-94aa-7447b53c718b.jpg)

Setting "install_options  => ['-notsilent']" in my puppet module does not really change anything (or am I using it the wrong way ?!)

My question now is:
Is it possible to send some notifications to the user desktop or is it not possible because puppet is running with the system account ?

**Comment by ferventcoder** [comment] 2016-06-06 23:45
> Is it possible to send some notifications to the user desktop or is it not possible because puppet is running with the system account ?

Bingo - I was just about to comment that you are likely running under the local system (`SYSTEM`) account, so you are not likely passing along things to the user you want.  You may need to redesign how you pop up your balloon tips so that it can be applied to all currently logged in users.

**Comment by ferventcoder** [comment] 2016-06-06 23:47
I'm going to close this as "won't fix" as it is not actually an issue we would fix. I don't see anything that is not working appropriately with Puppet / Chocolatey in this case. 

Unless you disagree with that, then feel free to respond.

**Closed by ferventcoder** 2016-06-06 23:47 UTC
Labels: Not Implementing / Invalid / Won't Fix

**Comment by ferventcoder** [comment] 2016-06-07 11:44
Feel free to respond if you run into other snags. I'm assuming you are doing something like this:  

* https://technet.microsoft.com/en-us/library/ff730952.aspx  
* https://bytecookie.wordpress.com/2011/12/28/gui-creation-with-powershell-part-2-the-notify-icon-or-how-to-make-your-own-hdd-health-monitor/
* http://techibee.com/powershell/system-tray-pop-up-message-notifications-using-powershell/1865

I was thinking about this some more and I think the issue is actually two-fold - windows services are usually background services, which means they have no interaction with the desktop. If you want to have interaction with the desktop, you will need to adjust the Puppet agent service so that it interacts with the desktop.

I love the idea of notifications in the tray menu! 

References:

* https://social.msdn.microsoft.com/Forums/vstudio/en-US/00ef16a2-746c-4675-8e9c-511ed27d9262/notifyicon-works-with-windows-forms-but-not-services?forum=clr
* http://stackoverflow.com/q/12857191/18475
* https://social.msdn.microsoft.com/Forums/windows/en-US/2ceda452-1576-4372-8406-a463333800f7/notifyicon-in-windows-services?forum=winforms

**Comment by peterbeck** [comment] 2016-06-07 11:52
Hi ferventcoder,
thanks for your suggestions. trayicon would be really cool, but most of the time it's working without ;-) Sometimes it would be a "nice to have feature".

Anyway, I found a workaround with "[msg](https://technet.microsoft.com/en-us/library/cc771903%28v=ws.11%29.aspx)". Just tested a minute ago and it seems to work
```
$block = { msg * "foo.li barfuss testmsg"}
Invoke-Command -ScriptBlock $block
```
![msg](https://cloud.githubusercontent.com/assets/561186/15856554/7388e9ea-2cb6-11e6-95c8-29bf5c76be8b.jpg)

with "*" it will send that message to all sessions. It's also possible to set timeouts. Not as nice as trayicons but at least it does its job.

**Comment by ferventcoder** [comment] 2016-06-07 11:56
You probably want that with a timeout as well? https://chocolatey.org/docs/development-environment-setup
