### ISSUE TITLE
Error in mixed environment with linux

### ISSUE THREAD

**Issue by chad-upton** [chocolatey/puppet-chocolatey#55] opened 2015-03-31 18:58 UTC
Running on Amazon Linux in EC2
Puppet master / agent setup.

If I install this module for our windows hosts, I get this error on our linux hosts when puppet is ran.

```
Error: Could not autoload puppet/provider/package/chocolatey: undefined method `+' for nil:NilClass
Error: Could not autoload puppet/type/package: Could not autoload puppet/provider/package/chocolatey: undefined method `+' for nil:NilClass
Error: Could not retrieve local facts: Could not autoload puppet/type/package: Could not autoload puppet/provider/package/chocolatey: undefined method `+' for nil:NilClass
Error: Failed to apply catalog: Could not retrieve local facts: Could not autoload puppet/type/package: Could not autoload puppet/provider/package/chocolatey: undefined method `+' for nil:NilClass
```

**Comment by ferventcoder** [comment] 2015-03-31 19:02
This is a duplicate of #54

**Comment by ferventcoder** [comment] 2015-03-31 19:03
I didn't have all of the details when I first set that one.

**Comment by chad-upton** [comment] 2015-03-31 19:04
No problem we rolled back to https://forge.puppetlabs.com/rismoney/chocolatey for the time being.

**Comment by ferventcoder** [comment] 2015-03-31 19:12
https://gist.github.com/ferventcoder/d5d9d9bb5c25548f24eb is a workaround I'm testing now.

**Comment by ferventcoder** [comment] 2015-03-31 19:33
Probably about five minutes from a new version being released.

**Closed** 2015-03-31 19:33 UTC
Labels: duplicate

**Comment by ferventcoder** [comment] 2015-03-31 19:50
And released. Let me know if you run into any more gating issues.

**Comment by chad-upton** [comment] 2015-03-31 20:05
Will do I'll test it again here shortly.

**Comment by chad-upton** [comment] 2015-04-01 19:44
Just wanted to tell ya everything looks good, appreciate the quick response.

**Comment by ferventcoder** [comment] 2015-04-01 19:56
Awesome! Hopefully the quality of this is great - plus you can use a gated approach to upgrade your choco clients, this will work with the older posh client versions (up to 0.9.8.33) as well as the newer compiled choco versions (0.9.9+).
